#!/bin/bash

CLASSPATH="target/prospero-1.0-SNAPSHOT.jar:target/dependency/*"
#TARGET_SERVER="target/wfly"
TARGET_SERVER="/Users/spyrkob/workspaces/set/eap/galleon/out"

if [ "$1" == 'install' ];
then
  java -cp "${CLASSPATH}" com.redhat.prospero.cli.actions.Provision "${TARGET_SERVER}" "target/prospero-repo"
elif [ "$1" == 'update' ];
then
  if [ -n "${2}" ];
  then
    java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -cp "${CLASSPATH}" com.redhat.prospero.cli.actions.Update "${TARGET_SERVER}" "target/prospero-repo" "${2}"
  else
    java -cp "${CLASSPATH}" com.redhat.prospero.cli.actions.Update "${TARGET_SERVER}" "target/prospero-repo"
  fi
elif [ "$1" == 'deploy' ];
then
    java -cp "${CLASSPATH}" com.redhat.prospero.cli.actions.DeployerArtifact "${2}" "${3}" "${4}" "${5}" "target/prospero-repo" "${@:6}"
else
  echo "Unrecognized command"
  exit 1;
fi
