#!/bin/bash

if [ -z "${PROSPERO_HOME}" ];
then
 full_path=$(realpath $0)
 PROSPERO_HOME=$(dirname $full_path)
fi
CLASSPATH="${PROSPERO_HOME}/prospero-cli/target/prospero-cli-1.0-SNAPSHOT.jar:${PROSPERO_HOME}/prospero-cli/target/dependency/*"
TARGET_SERVER="${PROSPERO_HOME}/out"

if [ "$1" == 'install' ];
then
  if [ -n "${3}" ];
  then
    TARGET_SERVER="$(greadlink -f ${3})"
    echo "Installing into ${TARGET_SERVER}"
  fi
  java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -cp "${CLASSPATH}" com.redhat.prospero.cli.actions.GalleonProvision "${2}" "${TARGET_SERVER}" "${4}"
elif [ "$1" == 'update' ];
then
  if [ $# -lt 2 ];
  then
    echo "Usage: prospero update <TARGET_SERVER>"
    exit 1
  fi
  if [ -n "${2}" ];
  then
    TARGET_SERVER="$(greadlink -f ${2})"
    if [ ! -d "${TARGET_SERVER}" ];
    then
      echo "There is no folder ${TARGET_SERVER}"
      exit 1
    fi
  fi
  if [ -n "${3}" ];
  then
    java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -cp "${CLASSPATH}" com.redhat.prospero.cli.actions.Update "${TARGET_SERVER}" "target/prospero-repo" "${3}"
  else
    java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -cp "${CLASSPATH}" com.redhat.prospero.cli.actions.Update "${TARGET_SERVER}"
  fi
elif [ "$1" == 'export' ];
then
  if [ $# -lt 3 ];
  then
    echo "Usage: prospero export <INSTALLED_SERVER> <EXPORT_FILE_NAME>"
    exit 1
  fi
  TARGET_SERVER="$(greadlink -f ${2})"
  java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -cp "${CLASSPATH}" com.redhat.prospero.cli.actions.InstallationExport "${TARGET_SERVER}" "${3}"
elif [ "$1" == 'restore' ];
  then
    if [ $# -lt 3 ];
    then
      echo "Usage: prospero restore <TARGET_DIRECTORY> <METADATA_BUNDLE>"
      exit 1
    fi
    TARGET_SERVER="$(greadlink -f ${2})"
    java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -cp "${CLASSPATH}" com.redhat.prospero.cli.actions.InstallationRestore "${TARGET_SERVER}" "${3}"
elif [ "$1" == 'history' ];
  then
    if [ $# -lt 2 ];
        then
          echo "Usage: prospero history <TARGET_DIRECTORY>"
          exit 1
        fi
    TARGET_SERVER="$(greadlink -f ${2})"
    java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -cp "${CLASSPATH}" com.redhat.prospero.cli.actions.InstallationHistory list "${TARGET_SERVER}"
elif [ "$1" == 'rollback' ];
  then
    if [ $# -lt 3 ];
    then
      echo "Usage: prospero rollback <TARGET_DIRECTORY> <REVISION>"
      exit 1
    fi
    TARGET_SERVER="$(greadlink -f ${2})"
    java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -cp "${CLASSPATH}" com.redhat.prospero.cli.actions.InstallationHistory revert "${TARGET_SERVER}" "${3}"
elif [ "$1" == 'compare' ];
  then
    if [ $# -lt 3 ];
    then
      echo "Usage: prospero compare <TARGET_DIRECTORY> <REVISION>"
      exit 1
    fi
    TARGET_SERVER="$(greadlink -f ${2})"
    java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -cp "${CLASSPATH}" com.redhat.prospero.cli.actions.InstallationHistory compare "${TARGET_SERVER}" "${3}"
elif [ "$1" == 'deploy' ];
then
    java -cp "${CLASSPATH}" com.redhat.prospero.cli.actions.DeployerArtifact "${2}" "${3}" "${4}" "${5}" "target/prospero-repo" "${@:6}"
else
  echo "Unrecognized command"
  exit 1;
fi
